### PR TITLE
2022-9-18 已完成

### PR DESCRIPTION
**Pull request by yenbigbear**

### CODE REVIEW

**Comment by yuaanlin** [comment]
Hi, thanks for the contribution!  You can convert this PR to **draft** if you're still working on it.

嗨，謝謝你貢獻的翻譯！ 如果你的翻譯工作尚未完成，請先將這個 PR 轉換為 **draft** 草稿。

**Review by yuaanlin — CHANGES_REQUESTED** [review]
Hi, thanks for the contribution! There is some terms need to be changed since it's generally used in Simplified Chinese, not Traditional Chinese.

嗨，謝謝你的貢獻！有一些翻譯的用詞需要進行修改，因為這些用詞是在簡體中文中使用的：

`用戶` -> `使用者`
`文件` -> `檔案`
`服務器` -> `伺服器`
`應用程序` -> `應用程式`
`響應` -> `回應`

**Comment by yenbigbear** [comment]
好的，謝謝你

**Review by yuaanlin — APPROVED** [review]
Nice work! Thanks for the contribution.

**Pull request merged**
